summary: XML-based font configuration tools
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.15.0
bin-url: https://github.com/leleliu008/uppm-package-repository-android-31-aarch64/releases/download/2025.01.22/fontconfig-2.15.0-android-31-arm64-v8a.release.tar.xz
bin-sha: e2a187e8f0bcad0d433065a76e86991f753f72116f9d7c1da44466ea86116285
